/**
 * Task-runtime vocabulary: the {@link TaskStart} a producer hands to
 * {@link TaskService.start} (identity + the `run()` starter), the
 * {@link TaskHooks} its work is driven through, and the snapshots/reads
 * consumers get back. Types only — the service lives in `./index.ts`.
 *
 * @module @deepseek-ai/dsh-tasks/types
 */

import type { Branded } from '@deepseek-ai/dsh-brand'
import type { Agent } from '@deepseek-ai/dsh-agent'
import type { SessionId } from '@deepseek-ai/dsh-session'

/**
 * Identifies one background task in the runtime-global registry. Generated by
 * {@link TaskService.start} as `<kind>-N` (per-kind counter) — kind-prefixed
 * so transcripts stay self-describing, sequential because the owner fence (not
 * id secrecy) is the isolation boundary.
 */
export type TaskId = Branded<'TaskId'>

/**
 * Brand a string as a {@link TaskId}.
 * @param id - the raw task-id string (the registry generates `<kind>-N`).
 * @returns the same string, branded; no validation is performed.
 */
export function TaskId(id: string): TaskId {
  return id as TaskId
}

/**
 * Task lifecycle. `running` → (`stopping` when cancellation was requested) →
 * exactly one terminal {@link TaskOutcome.status} (`completed`, `killed`,
 * `failed`). The vocabulary is generic and CLOSED — kind-specific meaning
 * (exit codes, stop reasons) rides in {@link TaskSnapshot.detail}, so the
 * registry never learns process or agent semantics.
 */
export type TaskStatus = 'running' | 'stopping' | 'completed' | 'killed' | 'failed'

/**
 * The terminal result a producer's {@link TaskHooks.done} resolves
 * with, mapped from the producer's own vocabulary (a process exit, a subagent
 * stop reason) into the registry's closed status set.
 */
export interface TaskOutcome {
  /** How the task ended: finished (`completed`), cancelled (`killed`), or broke (`failed`). */
  status: 'completed' | 'killed' | 'failed'
  /** Kind-specific detail rendered into status lines ('exit code: 3', 'max-tokens'). */
  detail?: string
  /**
   * Final output for FINAL-OUTPUT-ONLY kinds (no {@link TaskHooks.readOutput}),
   * read idempotently after the task settles. Stream kinds leave it unset —
   * their output is consumed incrementally through `readOutput`.
   */
  output?: string
}

/**
 * What a producer hands to {@link TaskService.start}: the task's identity and
 * owner (preflighted BEFORE any work starts), plus {@link run} — the starter
 * the runtime invokes only once preflight cannot fail anymore. The producer
 * stays the owner of its execution concerns (process streams, child agents);
 * the runtime owns ids, isolation, status, and completion fan-out. This
 * declare-then-execute split is what makes "work started but never got a
 * collectable id" structurally impossible.
 */
export interface TaskStart {
  /** Producer kind — also the id prefix (`bash`, `subagent`, …). Non-empty. */
  kind: string
  /** One-line model-facing label (the command; the delegation description). */
  label: string
  /**
   * The spawning agent. Its `session.header.id` becomes the task's owner
   * identity (read/kill/wait/list are fenced to that session), and its `ctx` scope
   * owns an async cleanup that cancels and awaits the task during disposal. It
   * must be the exact live instance currently registered under its agent id;
   * a stale object whose id has been reused is rejected before work starts.
   * `undefined` starts an UNOWNED task: open to any caller, alive until the
   * tasks service disposes.
   */
  owner?: Agent | undefined
  /**
   * Start the actual work and return its {@link TaskHooks}. Called EXACTLY
   * once, synchronously, after every preflight check (control-surface fence,
   * validation, owner-cleanup attach) has passed — nothing in the runtime can
   * fail after it returns, so the started work is always registered. A throw
   * here propagates with nothing registered; the producer owns any partial
   * cleanup of its own failed start.
   */
  run(): TaskHooks
}

/**
 * The live-work hooks a {@link TaskStart.run} returns: how the runtime
 * cancels the work, observes its settlement, and (for stream kinds) reads
 * its incremental output.
 */
export interface TaskHooks {
  /**
   * Request termination. Idempotent, synchronous, and must lead to
   * {@link done} settling; a throw propagates to the killer (fail loud — a
   * cancel that cannot even be requested is a producer bug). The optional
   * reason is `task_kill`'s logged reason, forwarded verbatim.
   */
  cancel(reason?: string): void
  /**
   * Settles with the terminal outcome at QUIESCENCE — after the producer has
   * released the task's resources (process exited, child agent disposed) —
   * not merely when the work finished. Must never reject; a rejection is
   * contained as a `failed` outcome and logged as a producer contract
   * violation. If `cancel` throws during teardown, the runtime may force-fail
   * only its registry record to avoid deadlock because this promise may never
   * settle; that fallback explicitly does not claim work quiescence.
   */
  done: Promise<TaskOutcome>
  /**
   * OPTIONAL incremental read (stream kinds): everything produced since the
   * previous call, formatted by the producer (truncation/spill notices
   * included). Consecutive calls never re-deliver output; the registry keeps
   * ONE consuming cursor per task, so v1's single intended reader is the
   * owning model. Absence marks a final-output-only kind (the method presence
   * IS the capability).
   */
  readOutput?(): string
}

/**
 * A read-only projection of one task, safe to hand to listeners and tools —
 * a fresh object per call, never live registry state.
 */
export interface TaskSnapshot {
  /** The registry-issued id (`<kind>-N`). */
  id: TaskId
  /** The producer kind the task was registered with. */
  kind: string
  /** The producer-supplied one-line label. */
  label: string
  /**
   * The owner's session id (`session.header.id`), for surfaces that must
   * reach the owning agent (the completion-notice injector); absent for
   * unowned tasks. Session ids are runtime-shared identifiers, not secrets —
   * the read/kill/wait/list FENCE is what isolation rests on. The shared
   * {@link SessionId} brand is preserved across this package boundary.
   */
  ownerSession?: SessionId
  /** Current lifecycle state. */
  status: TaskStatus
  /** Kind-specific status detail, present once the producer supplied one (usually terminal). */
  detail?: string
  /** Epoch ms when the task was registered. */
  startedAt: number
  /** Epoch ms when the task settled; absent while `running`/`stopping`. */
  finishedAt?: number
  /**
   * True once the terminal state has been (or is being) reported to the owner
   * through an explicit surface response — a `kill` call, or a `read`/`wait`
   * that returned the terminal state (including a wait pending at settlement).
   * Completion-notice surfaces suppress their notice when set, so the model
   * never gets a redundant "finished" for a task it just collected or killed.
   */
  reported: boolean
}

/**
 * One {@link TaskService.read}: the output text this read yields (may be
 * empty — the surface decides how to render "nothing new") plus the snapshot
 * taken after the read.
 */
export interface TaskRead {
  /**
   * Stream kinds: the consuming delta since the previous read. Final-output
   * kinds: empty while live, the terminal {@link TaskOutcome.output} (or
   * empty) once settled — idempotent, never consumed.
   */
  text: string
  /** The task's state at read time. */
  snapshot: TaskSnapshot
}

/** Completion callback registered via {@link TaskService.onTaskDone}. */
export type TaskDoneListener = (snapshot: TaskSnapshot) => void
